# Speech Emotion Recognition App - Core ML Script
# Autogenerated by Antigravity IDE

# Set TensorFlow environment variables first to suppress logs and warnings
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

# ==========================================
# 1. DEPENDENCY MANAGEMENT LAYER
# ==========================================
import subprocess
import sys
import importlib
import streamlit as st

@st.cache_resource(show_spinner=False)
def verify_dependencies():
    import importlib.util
    print("\n[SER App] Verifying system dependencies...")
    dependencies = {
        'librosa': 'librosa',
        'numpy': 'numpy',
        'soundfile': 'soundfile',
        'sklearn': 'scikit-learn',
        'tensorflow': 'tensorflow',
        'matplotlib': 'matplotlib',
        'plotly': 'plotly'
    }
    for import_name, package_name in dependencies.items():
        if importlib.util.find_spec(import_name) is None:
            print(f"[SER App] Installing missing package: '{package_name}' (this may take a few minutes)...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", package_name, "--quiet"])

verify_dependencies()

# ==========================================
# 2. STABLE FAULT LOGGER
# ==========================================
import logging
import traceback
import time

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_FILE_PATH = os.path.join(SCRIPT_DIR, 'app_error.log')

try:
    # Set up file logger by directly adding a FileHandler to bypass Streamlit's logging config
    logger = logging.getLogger()
    for h in logger.handlers[:]:
        if isinstance(h, logging.FileHandler) and h.baseFilename == os.path.normpath(LOG_FILE_PATH):
            logger.removeHandler(h)
    
    file_handler = logging.FileHandler(LOG_FILE_PATH, encoding='utf-8')
    file_handler.setLevel(logging.INFO)
    file_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    logger.addHandler(file_handler)
    logger.setLevel(logging.INFO)
except Exception as e:
    print(f"Failed to initialize file logger: {e}", file=sys.stderr)

# ==========================================
# 3. CORE IMPORTS & INITIALIZATION
# ==========================================
@st.cache_resource(show_spinner=False)
def initialize_backend():
    print("[SER App] Initializing backend engines...")
    print("[SER App] Backend configuration successfully loaded! Launching web interface...")

initialize_backend()

# ==========================================
# 4. AUDIO SPECTRUM PIPELINE (LIBROSA ENGINE)
# ==========================================
def extract_audio_features(file_path):
    """
    Loads target audio, resamples to 22050Hz, extracts a stacked 180-dimensional feature
    vector (40 MFCCs + 12 Chroma + 128 Mel Spectrogram) and reshapes to (180, 1).
    """
    import numpy as np
    import librosa
    import soundfile as sf
    try:
        # Load audio file with fixed 22050Hz sample rate
        y, sr = librosa.load(file_path, sr=22050)
        
        # Check if the audio is empty
        if len(y) == 0:
            raise ValueError("Empty audio signal sequence encountered.")
            
        stft = np.abs(librosa.stft(y))
        
        # Extract features and average over the time axis
        mfccs = np.mean(librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40).T, axis=0)
        chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sr).T, axis=0)
        mel = np.mean(librosa.feature.melspectrogram(y=y, sr=sr).T, axis=0)
        
        # Stack them to shape (180,)
        feature_vector = np.hstack((mfccs, chroma, mel))
        
        # Reshape to (180, 1)
        feature_vector_aligned = np.expand_dims(feature_vector, axis=-1)
        return y, sr, feature_vector_aligned
    except Exception as e:
        logging.error(f"Exception during feature extraction from {file_path}: {str(e)}")
        logging.error(traceback.format_exc())
        raise e

# ==========================================
# 5. ROBUST DEEP MODEL TOPOLOGY (CNN-1D)
# ==========================================
def build_ser_cnn_model(input_shape=(180, 1)):
    """
    Compiles standard 1D Convolutional Neural Network graph for Speech Emotion Recognition.
    """
    import tensorflow as tf
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import Conv1D, MaxPooling1D, BatchNormalization, Dropout, GlobalAveragePooling1D, Dense
    try:
        model = Sequential([
            Conv1D(64, kernel_size=3, padding='same', activation='relu', input_shape=input_shape),
            BatchNormalization(),
            MaxPooling1D(pool_size=2),
            Dropout(0.3),
            
            Conv1D(128, kernel_size=3, padding='same', activation='relu'),
            BatchNormalization(),
            MaxPooling1D(pool_size=2),
            Dropout(0.3),
            
            Conv1D(128, kernel_size=3, padding='same', activation='relu'),
            BatchNormalization(),
            Dropout(0.3),
            
            GlobalAveragePooling1D(),
            Dense(8, activation='softmax')
        ])
        model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
        return model
    except Exception as e:
        logging.error(f"Error compiling CNN-1D model structure: {str(e)}")
        logging.error(traceback.format_exc())
        raise e

@st.cache_resource(show_spinner=False)
def load_ser_model():
    """
    Attempts to load pre-trained weights from D:\MLTasks\ML task 1\models\trained_model.h5.
    Gracefully falls back to randomized initialization if any file load failures occur.
    """
    import tensorflow as tf
    # Suppress TensorFlow warnings and engine messages to keep logs clean
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
    os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
    
    models_dir = os.path.join(SCRIPT_DIR, 'models')
    weights_path = os.path.join(models_dir, 'trained_model.h5')
    
    status_msg = ""
    model = None
    
    if os.path.exists(weights_path):
        try:
            # 1. Attempt loading as a fully compiled Keras Model
            model = tf.keras.models.load_model(weights_path)
            status_msg = "Pre-trained Model (Full Graph Loaded Successfully)"
            logging.info("Pre-trained model loaded successfully via load_model.")
            return model, status_msg, False
        except Exception as e1:
            logging.warning(f"Failed to load full model graph: {str(e1)}. Attempting weights load...")
            try:
                # 2. Attempt building the model structure and loading weights manually
                model = build_ser_cnn_model(input_shape=(180, 1))
                model.load_weights(weights_path)
                status_msg = "Pre-trained Model (Weights Overlay Applied Successfully)"
                logging.info("Model weights loaded successfully onto compiled topology.")
                return model, status_msg, False
            except Exception as e2:
                logging.error(f"Failed to overlay model weights: {str(e2)}")
                logging.error(traceback.format_exc())
                
    # 3. Fallback: Initialize with random weights
    try:
        model = build_ser_cnn_model(input_shape=(180, 1))
        status_msg = "Demo Model Active (Fallback Random Weights - No pre-trained model file found)"
        logging.warning("Initialized model with random weights fallback.")
        return model, status_msg, True
    except Exception as e3:
        logging.error(f"Total fallback initialization failure: {str(e3)}")
        logging.error(traceback.format_exc())
        st.error("Severe Model Architecture Compiler Error. Check app_error.log.")
        sys.exit(1)

# ==========================================
# 6. PLAYBACK SIGNAL SCANNER (INTERACTIVE PLOTLY)
# ==========================================
def plot_waveform_plotly(y, sr):
    """
    Plots the time-domain waveform using Plotly and matching the dark violet theme.
    Downsamples the signal to ensure instant UI rendering.
    """
    import numpy as np
    try:
        # Downsample to ~2000 points to keep Plotly rendering fast and clean
        step = max(1, len(y) // 2000)
        y_downsampled = y[::step]
        time_axis = np.arange(len(y_downsampled)) * (step / sr)

        import plotly.graph_objects as go
        
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=time_axis,
            y=y_downsampled,
            mode='lines',
            line=dict(color='#a78bfa', width=1.5),
            hoverinfo='skip'
        ))
        
        fig.update_layout(
            plot_bgcolor='#0f0a24',
            paper_bgcolor='#0b071a',
            font=dict(color='#e2e0ed', family='Outfit, sans-serif'),
            margin=dict(l=10, r=10, t=35, b=10),
            height=240,
            xaxis=dict(
                title='Time (seconds)',
                gridcolor='#1f1a3a',
                zerolinecolor='#1f1a3a',
                showgrid=True,
                showline=True,
                linecolor='#7c3aed'
            ),
            yaxis=dict(
                title='Amplitude',
                gridcolor='#1f1a3a',
                zerolinecolor='#1f1a3a',
                showgrid=True,
                showline=True,
                linecolor='#7c3aed'
            ),
            showlegend=False,
            title=dict(
                text='Speech Signal Time-Domain Waveform',
                font=dict(size=14, color='#ffffff', weight='bold'),
                x=0.5,
                xanchor='center'
            )
        )
        return fig
    except Exception as e:
        logging.error(f"Plotly waveform plotting failed: {str(e)}")
        logging.error(traceback.format_exc())
        return None

# ==========================================
# 7. PROFESSIONAL STREAMLIT UI DESIGN
# ==========================================
def main():
    import numpy as np
    # Setup wide layout
    st.set_page_config(
        page_title="Speech Emotion Recognition Bot",
        page_icon="🤖",
        layout="wide",
        initial_sidebar_state="expanded"
    )

    if 'reset_counter' not in st.session_state:
        st.session_state.reset_counter = 0

    # Custom dark CSS injection (deep violet/accent cards)
    st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap');

    /* Body and Canvas Backgrounds */
    html, body, [data-testid="stAppViewContainer"], [data-testid="stHeader"] {
        background-color: #0b071a !important;
        background-image: radial-gradient(circle at 50% 50%, #150c33 0%, #080514 100%) !important;
        color: #e2e0ed !important;
        font-family: 'Outfit', sans-serif !important;
    }
    
    /* Glowing CSS cards */
    .glow-card {
        background: rgba(23, 15, 48, 0.7);
        border: 1px solid #7c3aed;
        border-radius: 16px;
        padding: 30px;
        box-shadow: 0 8px 32px 0 rgba(124, 58, 237, 0.25), 0 0 15px 0 rgba(124, 58, 237, 0.15);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        margin-bottom: 24px;
    }
    
    /* Goggles & Header glow styling */
    .app-title {
        font-size: 40px;
        font-weight: 700;
        color: #ffffff;
        text-shadow: 0 0 12px rgba(167, 139, 250, 0.7);
        text-align: center;
        margin-bottom: 5px;
    }
    
    .app-subtitle {
        font-size: 16px;
        color: #9ca3af;
        text-align: center;
        margin-bottom: 35px;
    }
    
    /* Prediction output details */
    .emotion-highlight {
        font-size: 32px;
        font-weight: 700;
        color: #10b981;
        text-shadow: 0 0 8px rgba(16, 185, 129, 0.6);
        text-transform: uppercase;
        margin-top: 5px;
    }
    
    /* Model loader status indicators */
    .badge {
        display: inline-block;
        padding: 5px 12px;
        border-radius: 6px;
        font-size: 12px;
        font-weight: 600;
        margin-bottom: 15px;
    }
    .badge-ok {
        background-color: rgba(16, 185, 129, 0.15);
        color: #34d399;
        border: 1px solid #10b981;
    }
    .badge-warn {
        background-color: rgba(245, 158, 11, 0.15);
        color: #fbbf24;
        border: 1px solid #f59e0b;
    }
    
    /* Emotion label classes */
    .emotion-lbl {
        font-weight: 600;
        color: #a78bfa;
    }
    
    /* Style file upload area */
    [data-testid="stFileUploaderDropzone"] {
        border: 2px dashed #7c3aed !important;
        background-color: rgba(21, 12, 51, 0.5) !important;
        border-radius: 12px !important;
    }
    
    /* Hide Streamlit header (Deploy button, Settings menu) and footer */
    [data-testid="stHeader"] {
        display: none !important;
    }
    footer {
        visibility: hidden !important;
    }

    /* Keyframes and Metric/Progress Bar additions */
    @keyframes pulse-glow {
        0% { box-shadow: 0 0 5px rgba(138, 43, 226, 0.4), 0 0 10px rgba(138, 43, 226, 0.2); border-color: #8a2be2; }
        50% { box-shadow: 0 0 15px rgba(186, 85, 211, 0.8), 0 0 20px rgba(186, 85, 211, 0.4); border-color: #ba55d3; }
        100% { box-shadow: 0 0 5px rgba(138, 43, 226, 0.4), 0 0 10px rgba(138, 43, 226, 0.2); border-color: #8a2be2; }
    }
    
    @keyframes fill-bar {
        from { transform: scaleX(0); }
        to { transform: scaleX(1); }
    }

    .metric-card {
        background: rgba(23, 15, 48, 0.7);
        border: 1px solid #8a2be2;
        border-radius: 12px;
        padding: 20px;
        animation: pulse-glow 3s infinite ease-in-out;
        margin-bottom: 20px;
        backdrop-filter: blur(12px);
    }
    .metric-title {
        font-size: 12px;
        color: #a78bfa;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        font-weight: 600;
    }
    .metric-value {
        font-size: 22px;
        color: #ffffff;
        font-weight: 700;
        margin-top: 6px;
        text-shadow: 0 0 8px rgba(167, 139, 250, 0.4);
    }
    .metric-sub {
        font-size: 11px;
        color: #9ca3af;
        margin-top: 4px;
    }

    /* Custom progress bar styles */
    .custom-progress-container {
        margin-bottom: 16px;
    }
    .custom-progress-header {
        display: flex;
        justify-content: space-between;
        margin-bottom: 4px;
        font-size: 14px;
    }
    .custom-progress-label {
        font-weight: 600;
        color: #a78bfa;
    }
    .custom-progress-value {
        font-weight: 600;
        color: #e2e0ed;
    }
    .custom-progress-bar-bg {
        background-color: #0f0a24;
        border: 1px solid #7c3aed;
        border-radius: 8px;
        height: 12px;
        width: 100%;
        overflow: hidden;
    }
    .custom-progress-bar-fill {
        background: linear-gradient(90deg, #8a2be2, #ba55d3);
        border-radius: 8px;
        height: 100%;
        width: var(--target-width);
        transform-origin: left;
        animation: fill-bar 1.2s ease-in-out forwards;
    }

    /* Custom button styling */
    .stButton>button {
        background: linear-gradient(135deg, #7c3aed, #9333ea) !important;
        color: white !important;
        border: none !important;
        border-radius: 8px !important;
        padding: 10px 24px !important;
        font-weight: 600 !important;
        transition: all 0.3s ease !important;
        box-shadow: 0 4px 15px rgba(124, 58, 237, 0.3) !important;
    }
    .stButton>button:hover {
        background: linear-gradient(135deg, #9333ea, #a855f7) !important;
        box-shadow: 0 6px 20px rgba(147, 51, 234, 0.5) !important;
        transform: translateY(-1px) !important;
    }
    .stButton>button:active {
        transform: translateY(1px) !important;
    }
    </style>
    """, unsafe_allow_html=True)

    # 1. Header Area
    st.markdown('<div class="app-title">🎙️ Speech Emotion Recognition (SER) Bot</div>', unsafe_allow_html=True)
    st.markdown('<div class="app-subtitle">Deep Learning Signal Classifier powered by 1D CNN & TensorFlow</div>', unsafe_allow_html=True)

    # 2. Setup model load and error-safe verification
    with st.spinner("Initializing Deep Neural Network configuration..."):
        model, model_status, is_fallback = load_ser_model()

    # 3. Upper Metrics Row (Placeholders)
    met_col1, met_col2 = st.columns(2)
    metric_placeholder1 = met_col1.empty()
    metric_placeholder2 = met_col2.empty()

    # Initial metric states
    metric_placeholder1.markdown("""
    <div class="metric-card">
        <div class="metric-title">Audio Ingestion Parameters</div>
        <div class="metric-value">Status: Idle</div>
        <div class="metric-sub">Awaiting .wav file ingestion...</div>
    </div>
    """, unsafe_allow_html=True)
    
    metric_placeholder2.markdown("""
    <div class="metric-card">
        <div class="metric-title">Inference & Diagnostics</div>
        <div class="metric-value">Engine: Ready</div>
        <div class="metric-sub">Awaiting model evaluation...</div>
    </div>
    """, unsafe_allow_html=True)

    # Sidebar parameters and indicators
    st.sidebar.image("https://img.icons8.com/nolan/128/artificial-intelligence.png", width=100)
    st.sidebar.markdown("### Model Diagnostics")
    
    if is_fallback:
        st.sidebar.markdown(f'<div class="badge badge-warn">⚠️ {model_status}</div>', unsafe_allow_html=True)
        st.sidebar.warning("App running with randomized fallback weights. Please place a valid 'trained_model.h5' inside 'models/' to load the pre-trained weights.")
    else:
        st.sidebar.markdown(f'<div class="badge badge-ok">✅ {model_status}</div>', unsafe_allow_html=True)
        st.sidebar.success("Pre-trained model loaded successfully! Inference values are ready.")

    st.sidebar.markdown("---")
    st.sidebar.markdown("### Pipeline Configurations")
    st.sidebar.info(
        "**Target Sampling:** 22050Hz\n\n"
        "**Feature Vector:** 40 MFCC + 12 Chroma + 128 Mel\n\n"
        "**Input Dimensions:** (180, 1)\n\n"
        "**Target Classification Nodes:** 8 soft-max targets"
    )

    # Main interaction cards
    col1, col2 = st.columns([1, 1], gap="large")

    # Dual-input audio ingestion variables
    source_audio_bytes = None
    file_extension = "wav"

    with col1:
        st.markdown('<div class="glow-card">', unsafe_allow_html=True)
        st.subheader("🎵 Input Audio Track")
        st.write("Provide an audio asset via file drag-and-drop or use the live recorder container to trigger neural emotion recognition:")
        
        tab1, tab2 = st.tabs(["📁 File Upload", "🎙️ Live Microphone Recorder"])
        
        with tab1:
            uploaded_file = st.file_uploader(
                "Select Audio File", 
                type=["wav", "mp3", "m4a"], 
                help="Accepts WAV, MP3, and M4A formats.",
                key=f"uploader_{st.session_state.reset_counter}"
            )
            if uploaded_file is not None:
                source_audio_bytes = uploaded_file.read()
                _, ext = os.path.splitext(uploaded_file.name)
                if ext:
                    file_extension = ext.lstrip('.')
                    
        with tab2:
            audio_record = st.audio_input(
                "Record your voice sample live",
                key=f"recorder_{st.session_state.reset_counter}"
            )
            if audio_record is not None:
                source_audio_bytes = audio_record.read()
                file_extension = "wav"
        
        if source_audio_bytes is not None:
            # Play the audio back
            st.audio(source_audio_bytes, format=f'audio/{file_extension}')
            
            # Reset button right after player for easy access
            if st.button("🗑️ Reset / Clear Screen", use_container_width=True):
                st.session_state.reset_counter += 1
                st.rerun()
            
            # Temporary store uploaded file path for librosa load
            temp_path = os.path.join(SCRIPT_DIR, f"temp_upload.{file_extension}")
            try:
                with open(temp_path, "wb") as f:
                    f.write(source_audio_bytes)
                
                # Measure feature extraction time
                start_process = time.perf_counter()
                with st.spinner("Extracting audio signals & computing acoustic features..."):
                    # Extract signals
                    y, sr, features = extract_audio_features(temp_path)
                process_time = (time.perf_counter() - start_process) * 1000
                    
                st.success("Signal preprocessing completed successfully!")
                
                # Update top left metric card
                metric_placeholder1.markdown(f"""
                <div class="metric-card">
                    <div class="metric-title">Audio Ingestion Parameters</div>
                    <div class="metric-value">22,050 Hz | {len(y)/sr:.2f}s</div>
                    <div class="metric-sub">Features Shape: {features.shape} Output Array</div>
                </div>
                """, unsafe_allow_html=True)
                
                # Show signal information
                st.markdown("##### Signal Parameters:")
                st.write(f"- **Sample Rate:** {sr} Hz (Resampled from original)")
                st.write(f"- **Duration:** {len(y)/sr:.2f} seconds")
                st.write(f"- **Shape of Extracted Features:** {features.shape} (Feature Length, Channels)")
                
                # Render the interactive Plotly waveform plot
                waveform_fig = plot_waveform_plotly(y, sr)
                if waveform_fig:
                    st.plotly_chart(waveform_fig, use_container_width=True)
                
            except Exception as e:
                st.error("Failed to process target audio track. Details logged to app_error.log.")
                logging.error(f"Audio processing failure: {str(e)}")
                logging.error(traceback.format_exc())
            finally:
                # Cleanup temp file
                if os.path.exists(temp_path):
                    try:
                        os.remove(temp_path)
                    except Exception as e_del:
                        logging.warning(f"Failed to delete temp file {temp_path}: {e_del}")
                    
        st.markdown('</div>', unsafe_allow_html=True)

    with col2:
        st.markdown('<div class="glow-card">', unsafe_allow_html=True)
        st.subheader("🎯 Emotion Classification Output")
        
        emotion_labels = ['neutral', 'calm', 'happy', 'sad', 'angry', 'fearful', 'disgust', 'surprised']
        
        if source_audio_bytes is not None and 'features' in locals():
            try:
                # Expand shape to (batch, features, channels) i.e. (1, 180, 1)
                input_tensor = np.expand_dims(features, axis=0)
                
                # Measure model inference time
                start_inf = time.perf_counter()
                with st.spinner("Running Inference on model layers..."):
                    prediction = model.predict(input_tensor)[0]
                inference_time = (time.perf_counter() - start_inf) * 1000
                
                max_idx = np.argmax(prediction)
                predicted_emotion = emotion_labels[max_idx]
                confidence = prediction[max_idx] * 100
                
                # Update top right metric card
                metric_placeholder2.markdown(f"""
                <div class="metric-card">
                    <div class="metric-title">Inference & Diagnostics</div>
                    <div class="metric-value">{predicted_emotion.upper()} ({confidence:.1f}%)</div>
                    <div class="metric-sub">Latency: {inference_time:.1f} ms | Model: 1D CNN</div>
                </div>
                """, unsafe_allow_html=True)
                
                # Visual Highlight of Predicted Emotion
                badge_class = f"emotion-{predicted_emotion}"
                st.markdown(f'<div class="emotion-badge {badge_class}">{predicted_emotion}</div>', unsafe_allow_html=True)
                st.markdown(f'Top Recognized Emotion: <div class="emotion-highlight">{predicted_emotion} ({confidence:.1f}%)</div>', unsafe_allow_html=True)
                
                st.markdown("---")
                st.write("##### Probability Distribution Across Softmax Output Nodes:")
                
                # Print probability bars for all targets using custom animated HTML/CSS
                for idx, emotion in enumerate(emotion_labels):
                    prob = prediction[idx]
                    pct = prob * 100
                    st.markdown(f"""
                    <div class="custom-progress-container">
                        <div class="custom-progress-header">
                            <span class="custom-progress-label">{emotion.capitalize()}</span>
                            <span class="custom-progress-value">{pct:.1f}%</span>
                        </div>
                        <div class="custom-progress-bar-bg">
                            <div class="custom-progress-bar-fill" style="--target-width: {pct}%;"></div>
                        </div>
                    </div>
                    """, unsafe_allow_html=True)
                    
            except Exception as e:
                st.error("Error encountered during Model Inference. Check app_error.log.")
                logging.error(f"Inference failure: {str(e)}")
                logging.error(traceback.format_exc())
        else:
            st.info("Provide an audio asset via file drag-and-drop or use the live recorder container to trigger neural emotion recognition.")
            
        st.markdown('</div>', unsafe_allow_html=True)

if __name__ == '__main__':
    main()
